name: Docker Image CI
on:
  push:
    branches: [ main, '*' ]
jobs:
  setup-docker:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2

    - name: Set up QEMU
      uses: docker/setup-qemu-action@v1
      with:
        platforms: all

    - name: Set up Docker Buildx
      id: buildx
      uses: docker/setup-buildx-action@v1

    - name: Available platforms
      run: echo ${{ steps.buildx.outputs.platforms }}

    - name: Login to DockerHub Registry
      run: echo ${{ secrets.DOCKERHUB_TOKEN }} | docker login -u ${{ secrets.DOCKERHUB_USER }} --password-stdin
  
  build-default:
    runs-on: ubuntu-latest
    needs: [setup-docker]
    steps:
    - uses: actions/checkout@v2
    - name: Build and push multi-platform Docker image
      run: make multi-default

  build-arm64:
    runs-on: ubuntu-latest
    needs: [setup-docker]
    steps:
    - uses: actions/checkout@v2
    - name: Build and push multi-platform Docker image
      run: make multi-arm64
